# Generated by Django 2.0.5 on 2018-05-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180521_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='qc_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='qc_pass',
            field=models.BooleanField(default=False),
        ),
    ]
