# Generated by Django 2.0.5 on 2018-05-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180528_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='app_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='answers',
            name='qc_pass',
            field=models.BooleanField(default=True),
        ),
    ]
