# Generated by Django 2.0.5 on 2018-05-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180529_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='app_url',
            field=models.CharField(max_length=200),
        ),
    ]
